esphome:
  name: 'kalfire-example'

esp32:
  board: esp32-s3-devkitc-1

logger:
web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: ./components

# switch:
#   - platform: template
#     name: Enable flame
#     id: enable_flame
#     optimistic: true

#   - platform: template
#     name: Enable ECO mode
#     id: enable_eco_mode
#     optimistic: true

i2c:
  sda: GPIO2
  scl: GPIO1
  scan: true
  id: i2c_bus

gp8403:
  id: dac_gp8403
  voltage: 10V
  address: 0x59

output:
  - platform: gp8403
    id: my_gp8403_output_1
    gp8403_id: dac_gp8403
    channel: 0
  - platform: gp8403
    id: my_gp8403_output_2
    gp8403_id: dac_gp8403
    channel: 1

# number:
#   - platform: template
#     name: Flame height
#     id: flame_height
#     min_value: 1
#     max_value: 8
#     step: 1
#     optimistic: true
#     restore_value: true

switch:
  - platform: kalfire
    kalfire_id: my_kalfire

kalfire:
  id: my_kalfire
  output: my_gp8403_output_1
  # flame_height: flame_height
  # enable_flame: enable_flame
  # eco_mode: enable_eco_mode
