esphome:
  name: 'kalfire-example'

esp32:
  board: esp32-s3-devkitc-1

logger:
web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: ./components

i2c:
  sda: GPIO2
  scl: GPIO1
  scan: true
  id: i2c_bus

gp8403:
  id: dac_gp8403
  voltage: 10V
  address: 0x59

output:
  - platform: gp8403
    id: my_gp8403_output_1
    gp8403_id: dac_gp8403
    channel: 0
  - platform: gp8403
    id: my_gp8403_output_2
    gp8403_id: dac_gp8403
    channel: 1

switch:
  - platform: kalfire
    flame:
      name: Enable flame
    eco_mode:
      name: Enable ECO mode

number:
  - platform: kalfire
    flame_height:
      name: Flame height

kalfire:
  id: my_kalfire
  output: my_gp8403_output_1

